version: 2

updates:
  # Composer
  - package-ecosystem: composer
    directory: /
    schedule: { interval: daily }
    allow:
      - dependency-type: all # Direct & indirect updates for all packages
    versioning-strategy: widen
    open-pull-requests-limit: 15
    assignees:
      - benjaminmal

  # GitHub Action
  - package-ecosystem: github-actions
    directory: /
    schedule: { interval: daily }
    open-pull-requests-limit: 15
    assignees:
      - benjaminmal
